### ISSUE TITLE
Frequent crashes in Eclipse IDE for C/C++ Developers 2023-12

### ISSUE THREAD

**Issue by stevew3344** [eclipse-packaging/packages#101]
Since about 4/2023 I've been experiencing frequent crashes on the Eclipse IDE; these crashes generate core files and crash logs. As suggested by the crash text output, these were reported to https://github.com/adoptium/adoptium-support/issues/882. The basic suggestions from there were to upgrade to the latest versions of Eclipse, Java and GTK3.

The crashes persist, and often occur multiple times per day. The most recent response from that forum was to contact Eclipse IDE (https://github.com/adoptium/adoptium-support/issues/882#issuecomment-1849360714).

I'm running:
Eclipse IDE for C/C++ Developers (includes Incubating components)
Version: 2023-12 (4.30.0)
Build id: 20231201-2043
OS: Linux, v.3.10.0-957.27.2.el7.x86_64, x86_64 / gtk 3.22.30
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.9+9
Java version: 17.0.9

My latest crash log is attached.

Thank you for any suggestions.
[hs_err_pid396000.log](https://github.com/eclipse-packaging/packages/files/13677082/hs_err_pid396000.log)

**Comment by merks** [comment]
I've seen a number of issues in the Platform related to crashes on LInux:

- https://github.com/eclipse-platform/eclipse.platform.swt/issues/1155
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/1076

Such crashes related to SWT's GTK support are best reported there.
