### ISSUE TITLE
Review and remove Help -> Report a bug menu item contributed by Mylyn

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-packaging/packages#102]
In the current EPP configuration Mylyn contributes a help -> report a bug item that opens an empty dialog. See https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/338

**Comment by mjmeijer** [comment]
See my comment here: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/338#issuecomment-1887118151
