### ISSUE TITLE
Update require Java 21

### ISSUE THREAD

**Issue by merks** [eclipse-packaging/packages#130]
@jonahgraham 

I will coordinate the necessary changes with the JustJ changes.

Note that the first 2024-06 M1 content build using the restructured infrastructure was successful:

https://download.eclipse.org/justj/?file=technology/epp/staging

BTW, I've never seen this before:

![image](https://github.com/eclipse-packaging/packages/assets/208716/655eb82c-2973-4975-a229-e68136707682)

I assume this should be updated to 21 too.

**Comment by jonahgraham** [comment]
**`<vmArgs>`**

Yes, this needs updating to fail early if wrong Eclipse is present.

**`<vm>` section**
I assume so - they were updated for all previous updates and  correspond to this part of the UI:

![image](https://github.com/eclipse-packaging/packages/assets/679236/90f47dd4-eb52-4c0d-ad41-81228ce7772c)

However I don't know if there is a purpose for the build. The Platform's product file does not have this [info](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/636175ed0373de8671fa93716b90dddf4f2840dd/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product#L28). PDE uses this section to populate the the launch configuration, so keeping it in doesn't seem like a bad idea:

![image](https://github.com/eclipse-packaging/packages/assets/679236/22b236af-2a86-4642-ad88-938a54672c46)


For reasons of probable simple oversight DSL still has Java 11 in that section. It should probably be synchronized too:

https://github.com/eclipse-packaging/packages/blob/42922409eb441e9006db069e817a5a134c74e2fe/packages/org.eclipse.epp.package.dsl.product/epp.product#L59-L61

**Comment by merks** [comment]
The latest staging build includes all the support for Java 21:

https://download.eclipse.org/justj/?file=technology/epp/staging
