### ISSUE TITLE
Ensure that there always exists a staging repository

### ISSUE THREAD

**Issue by merks** [eclipse-packaging/packages#142]
The product catalog generator is now generating staging products which relies on the following URL always existing:

https://download.eclipse.org/technology/epp/staging/repository/

It seems the process for promoting a milestone removes the entire staging folder.  Could that be amended to retain at least the staging/repository?

**Comment by jonahgraham** [comment]
AFAICT my update to scripts worked. The https://download.eclipse.org/technology/epp/staging/repository/ is retained on promotion and the correctly promoted p2 repo is here https://download.eclipse.org/technology/epp/packages/2024-06/202405021000/
