### ISSUE TITLE
Add branding

### ISSUE THREAD

**Issue by erik-brangs** [eclipse-packaging/packages#15]
As of now, there doesn't seem to be any branding in the repositories. The eclipse-packaging organization uses a default GitHub icon (like I am using right now). It would be nice if branding were added so that the organization is instantly recognizable as part of Eclipse, e.g. like https://github.com/eclipse-platform or https://github.com/eclipse-jdt .

**Comment by merks** [comment]
Yes, I did that for my projects too:  

- https://github.com/eclipse-justj
- https://github.com/eclipse-emf

But you can't do this yourself. You need a helpdesk issue and you must ask precisely for what you want, like I did here for EMF:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2794#note_1090843

**Comment by jonahgraham** [comment]
100% - this is needed, hopefully we can complete it by the time we get 2023-06 out the door and this repo becomes more visible. Although that may happen sooner than 2023-06 release date due to #14

I added this item to the TODO list in #1

**Comment by merks** [comment]
I've have created the following issue/request to get the ball rolling:

https://gitlab.eclipse.org/eclipsefdn/marketing/-/issues/2315

**Comment by jonahgraham** [comment]
For #155 I added this todo item for the manual smoke testing:

- [ ] Verify branding improvements added in https://github.com/eclipse-packaging/packages/issues/15 have applied successfully to built products
