### ISSUE TITLE
The eclipse-sign-jar profile seems overused

### ISSUE THREAD

**Issue by merks** [eclipse-packaging/packages#152]
@jonahgraham 

I was looking at this item:

- [x] Check that there are no unexpected warnings in the console output. Especially look for warnings about failure to sign.
  - There are so many warnings now in the build due to changes in how Maven and Tycho report. To identify unique warnings a command like this is useful: `curl https://ci.eclipse.org/packaging/job/epp/job/master/3/consoleText | gunzip  | grep WARNING | perl -pe 's/^\[[^\]]+\]//g' | sort -u > warning` (update build number in curl command)

Note that you can always use this URL for the above instruction:

https://ci.eclipse.org/packaging/job/epp/job/master/lastBuild/consoleText

Looking for warnings, I see it's quite clean but I see these:

```
[2024-05-02T07:37:44.103Z] [WARNING] The requested profile "eclipse-sign-jar" could not be activated because it does not exist.
```

I think that's because we use that profile in all the maven builds but I think we only need/should specify it for the first build which build features and not for the subsequent builds:

![image](https://github.com/eclipse-packaging/packages/assets/208716/96950fb5-f488-444d-a207-5ab5b534145c)

Does that make sense?

**Comment by jonahgraham** [comment]
Yes it does - I had actually just been creating a PR on that, I'll link it here.

**Comment by jonahgraham** [comment]
Thanks to this last step and all the work you did during M1, the build is now warning free. The checklist has been updated to say `Check that there are no warnings in the console output.`

**Comment by merks** [comment]
I love warning free builds!
