### ISSUE TITLE
Cannot delete / fix an incorrect Checkstyle link to checkstyle.xml file.

### ISSUE THREAD

**Issue by leerho** [eclipse-packaging/packages#157]
### Configuration
Using Eclipse IDE for Java 2024-03 (4.31.0) Build id: 20240307-1437
-   A brand new installation in a brand new workspace 
-   I only installed the Checkstyle plugin: 10.14.2.202403262245 net.sf.eclipsecs.feature.group
-   Imported only one existing java/maven root project with 2 sub-projects

Running on Apple MacBook Pro, Apple M1 Pro chip, macOS Sonoma 14.4.1

### Description / Steps to Reproduce
I accidentally inserted an incorrect location for a checkstyle.xml file, which I discovered later.
But now I cannot delete it or fix it. 

**Steps to Reproduce:**
- Right-click on project, select Properties / Checkstyle
    - The "Location" box at the top has a red X (of course) with the incorrect location listed 
- Select "Local Check Configurations"
- Select the bad "Check Configuration" / Remove
- First I get a Confirm Delete pop-up, click "Yes"
- Then I get this error message:

> The Check Configuration "\<file name\>" is currently in use by a project.
> It must be removed from all project configurations before it can be deleted.

This puts me in an endless loop.  I have tried deactivating checkstyle in two projects (the only two), to no avail.  I have unclicked the box "Checkstyle active for this project".  Nothing I do allows me to correct the entry.  I guess I am forced to uninstall the Checkstyle plugin and reinstall it.

**Comment by merks** [comment]
What makes you think this a generic eclipse problem rather than specifically a problem with checkstyle?

I recommend you report the problem here

https://github.com/checkstyle/eclipse-cs/issues

The developers of that cool project will know better if there is a problem they can fix or it there is some problem in some eclipse framework that needs to be fixed. 

The packaging project literally just packages content provided by other projects so we definitely cannot fix it here. 

It would be helpful if you posted a link here to the issue you create.

**Comment by leerho** [comment]
> What makes you think this a generic eclipse problem rather than specifically a problem with checkstyle?

- I searched online to where to report Eclipse bugs and it brought me here.  If I search for Checkstyle bugs it will send me to the GitHub.com/checkstyle site, which isn't correct either.  
- I am a very long-time user of Eclipse. Yet, I have no way of knowing what menus are designed by Eclipse or a 3rd party, such as Checkstyle, nor is it easy to figure out.  Even 3rd party plugins designed for Eclipse must design their plugins subject to design and logic rules dictated by Eclipse.  
- Only Eclipse insiders know this kind of information. Why would you assume that an Eclipse user would know this?

Nonetheless, **thank you** for pointing me to the proper place to report this issue.  I will do that and place a link here.

**Comment by merks** [comment]
It’s a HUGE challenge to figure out where to report a problem so reporting here is really okay.  If have good tricks for finding right places. 😄

**Comment by leerho** [comment]
See [https://github.com/checkstyle/eclipse-cs/issues/700](https://github.com/checkstyle/eclipse-cs/issues/700)
