### ISSUE TITLE
Consistent branding of EPP's features?

### ISSUE THREAD

**Issue by merks** [eclipse-packaging/packages#159]
Only two of the products have special images for the branding:

![image](https://github.com/eclipse-packaging/packages/assets/208716/f0f10ac8-7b0e-4a98-814e-3de1694c00f4)

The committers one is actually just the standard eclipse logo.  

JEE uses this:

![image](https://github.com/eclipse-packaging/packages/assets/208716/96a76023-409d-4fb1-9b27-f348c785d323)

For JEE those things are also used in all these places:

![image](https://github.com/eclipse-packaging/packages/assets/208716/e9001e21-6752-4b8d-838e-05eb4d91f885)

Though the only place I see that image is here in the about dialog for the branding category:

![image](https://github.com/eclipse-packaging/packages/assets/208716/0712b8a7-514a-49f3-b6e2-82156c7d5d69)

For the purpose of branding the EPP features specifically in the about dialog, I think it might be nicer to use the new EPP logo:

https://avatars.githubusercontent.com/u/128705312?s=200&v=4

But of course only for the uses in the about.ini.

@jonahgraham @nitind 

What do you think?

**Comment by merks** [comment]
Here is how it would/will look:

![image](https://github.com/eclipse-packaging/packages/assets/208716/ecbde390-1024-40fa-bb96-6d50751f1313)

**Comment by nitind** [comment]
@merks I'm for it because 1) consistency 2) relevance as we go further into the Jakarta EE era.

**Comment by jonahgraham** [comment]
@merks +1 for this change.
