### ISSUE TITLE
Packages for Windows on ARM

### ISSUE THREAD

**Issue by HannesWell** [eclipse-packaging/packages#162]
Now that the Eclipse Platform supports Windows on ARM (WoA) natively I think it would be good to provide packages for that environment too.

But since there are no Temurin Releases for WoA yet (https://github.com/adoptium/adoptium-support/issues/616) and we are late in the release-cycle, I assume we won't have it for the June release, do we?

Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/577

**Comment by chirontt** [comment]
@merks what about having WoA packages without any embedded JustJ JRE? is that also too much a special case?

**Comment by merks** [comment]
It's late in the cycle.  The inclusions of JustJ in the products would need to be conditional on the architecture:
```
      <feature id="org.eclipse.justj.epp" installMode="root"/>
```

We really **need** this:

https://github.com/adoptium/adoptium-support/issues/616

It always seems just around the corner but also with no end in sight.

**Comment by jonahgraham** [comment]
The 2024-12 M2 EPP build that contains WoA packages is now available for testing. If you have access to WoA, please let me know if these new packages work. See announcement in https://www.eclipse.org/lists/epp-dev/msg06939.html

**Comment by HannesWell** [comment]
> The 2024-12 M2 EPP build that contains WoA packages is now available for testing. If you have access to WoA, please let me know if these new packages work.

In my initial testing it worked well. I'll test/use it further but won't expect late to detect issues.

Thanks a lot @merks and thank you @jonahgraham for all the support.
It's great that all of this is possible.🚀
