### ISSUE TITLE
Wrong splash screen, without "IDE" for 2024-06

### ISSUE THREAD

**Issue by howlger** [eclipse-packaging/packages#178]
For the 2024-06 release the wrong [splash screen](https://github.com/eclipse-packaging/packages/blob/master/packages/org.eclipse.epp.package.common/splash.bmp) is included: the splash screen without "IDE" is for the Eclipse project, but the IDE packages should have the splash screen with "IDE".

See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3963#note_2342954

**Comment by merks** [comment]
I guess when I asked and followed the instructions, it just wansn't clear which

**Comment by merks** [comment]
@jonahgraham 

I think we can just merge this immediately and start another build immediately, right?

**Comment by merks** [comment]
A new build has started:

https://ci.eclipse.org/packaging/job/epp/job/master/82/

**Comment by jonahgraham** [comment]
> I think we can just merge this immediately and start another build immediately, right?

Yes :-) and thanks for handling this!

**Comment by merks** [comment]
While we are on this topic,  where will I find images for 2024-09, 2024-12, and so on?

**Comment by jonahgraham** [comment]
https://github.com/eclipse-packaging/packages/blob/17f8c753c9f50b4b13e8030d0d19a70207227c94/packages/org.eclipse.epp.package.common/splash/INSTRUCTIONS.md#L14

or as someone has nicely put them here as an alternative https://github.com/eclipse-platform/eclipse.platform/tree/master/platform/org.eclipse.platform/splashscreens2024

**Comment by merks** [comment]
I've created a bookmark.  👍

**Comment by jonahgraham** [comment]
I think we are done here - the splash screen looks correct now.

Thanks @howlger for taking the time to file the report! Thanks @merks for rolling out the fix quickly!

**Comment by merks** [comment]
Good teamwork all around!  🥇
