### ISSUE TITLE
Eclipse is crashing while importing any package.

### ISSUE THREAD

**Issue by nitinsreevstv** [eclipse-packaging/packages#182]
Hey Team, I am using UBUNTU 21 and my java version is 21. I am creating a selenium framework using quickstart maven archetype. In my Framework, When I try to import selenium package, The eclipse is crashing. I'm sharing the videos with you. Please assist me for this problem. 
Email - psri7080@gmail.com

https://github.com/eclipse-packaging/packages/assets/76206822/63cb080a-561b-49c0-a834-d91bbe47a600

**Comment by howlger** [comment]
It looks like it crashes the first time the browser widget is used. Does setting one of the following environment variables before launching Eclipse help?

- [`WEBKIT_DISABLE_DMABUF_RENDERER=1`](https://stackoverflow.com/a/78358707/6505250) or
- [`GDK_BACKEND=x11`](https://stackoverflow.com/a/78357050/6505250)

**Comment by merks** [comment]
I'll assume this is addressed.  If there is a new problem, it would need to be fixed in the Platform.

**Comment by nitinsreevstv** [comment]
I have tried, as hawlger said. Not working for me.

**Comment by nitinsreevstv** [comment]
I tried this to run vsCode :- https://stackoverflow.com/questions/66583287/vscode-crashes-when-starting-up-in-ubuntu

**Comment by howlger** [comment]
> VScode was also crashing, so I tried this to run vsCode :- https://stackoverflow.com/questions/66583287/vscode-crashes-when-starting-up-in-ubuntu

This is the wrong place and there is not enough information to help you.

**Comment by nitinsreevstv** [comment]
> > VScode was also crashing, so I tried this to run vsCode :- https://stackoverflow.com/questions/66583287/vscode-crashes-when-starting-up-in-ubuntu
> 
> This is the wrong place and there is not enough information to help you.


No, I'm saying that after applying this, working fine now. 
Can you please tell me what was the issue.

**Comment by nitind** [comment]
Can you tell us where you got your Eclipse from? It sounds like your issue was not with a package from eclipse.org, but rather something made with a packaging system like app snaps.

**Comment by nitinsreevstv** [comment]
@nitind I downloaded from the Ubuntu App center and the Java version is 21.

**Comment by nitinsreevstv** [comment]
@merks Still crashing. Please open this and resolve this problem

**Comment by merks** [comment]
There is almost no problem that can be fixed by EPP because it's content is just 99% just accumulating content from other projects.  That's why you've been told:

> This is the wrong place and there is not enough information to help you.

Any one of these issues might be the same problem as yours:

https://github.com/eclipse-platform/eclipse.platform.swt/issues?q=is%3Aissue+is%3Aopen+crash

But given the lack of details, it's not entirely clear.

**Comment by nitinsreevstv** [comment]
Thanks @merks !! I'm checking them
