### ISSUE TITLE
Add Mylyn to packages

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-packaging/packages#19]
Mylyn is back in 2023-06 M2. This issue is to track how/if we add it to the individual packages again.

Commit 711cdb499d09bd3cdcc5c1c722872f84fa6ffbd0 was the one that removed it, but at that time different packages had a bunch of different subsets of Mylyn, with some packages having nothing.

Is there a single Mylyn feature that can simply be included everywhere that contains all or most all the key functionality?

I am soliciting feedback on the mailing list for a way forward.

**Comment by guw** [comment]
+1 for committers

**Comment by wimjongman** [comment]
The key functionality is the internal rich task system. If you get used to it, the context system is very nice (it remembers the open files for a specific task). Also, the new GitHub and, Jenkins interfaces are great.

**Comment by jonahgraham** [comment]
I have put together a PR in #24 which includes the reasoning for why I have included/excluded each of the mylyn features.

**Comment by jonahgraham** [comment]
@merks - I see in [gerrit](https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/202144) you added `org.eclipse.oomph.setup.mylyn` to SimRel - I assume that doesn't need to be in all the EPPs? If it should be in all EPPs, then should other `org.eclipse.oomph.setup.*` also be?

**Comment by merks** [comment]
No don't add any other Oomph things to any packages.   Thanks for asking.  😄
