### ISSUE TITLE
Download for 2024-09 (4.33.0) does not show sha512 hash

### ISSUE THREAD

**Issue by JanMosigItemis** [eclipse-packaging/packages#211]
## Steps to reproduce

Go to https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-09/R/eclipse-java-2024-09-R-win32-x86_64.zip and click the "SHA-512" button.

I expected: sha512 hash code of the file.

But got: Unable to locate sums for this file (3120).

## Tested under this environment:
* OS & Version: Microsoft Windows [Version 10.0.22621.4037] (Windows 11)
* Chrome 128.0.6613.138
* Eclipse IDE / Platform version: 20240905-0614

**Comment by merks** [comment]
I see, it looks like this:

![image](https://github.com/user-attachments/assets/12680a56-9479-483c-9196-b4701d9fa447)

**Comment by merks** [comment]
I've been told this is the same issue as this one:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5011
