### ISSUE TITLE
Copy Paste of Project results in new copied project not appearing in Working Sets

### ISSUE THREAD

**Issue by C4J** [eclipse-packaging/packages#254]
In previous versions of Eclipse, if you use working sets and use copy/paste to duplicate your project with a new name, then the copied project would appear in the working set called Other. Now it does not appear anywhere.

I am running Eclipse 2024-12 EE on macOS Sonoma 15.1.1

Creating a new project in the standard way does appear in the selected Working Set.

If you want to see the copy/pasted new project you have to go into the properties of an existing working set and "add" the new project to it. 

Otherwise it's completely invisible.

**Comment by merks** [comment]
The packaging project just composes the content of other projects.  Please open an issue here instead

https://github.com/eclipse-platform/eclipse.platform.ui/issues

Be specific about which view and perspective is involved.   Include screen captures.  If I recall correctly, many of the wizards let you choose the working set for the new project.  So please be specific about exactly which wizard you used.
