### ISSUE TITLE
The Eclipse Installer 2024‑12 R fails to install for "all users" on a Windows 11 PC

### ISSUE THREAD

**Issue by Dirk-LG** [eclipse-packaging/packages#264]
Hi,

this topic is not new, however not addressed by the current release, too.
The reason behind is that many users do not want to work with full administrator privileges all the time.

Today I installed Eclipse 2024-12 using the Windows installer "eclipse-inst-jre-win64.exe" and got the same issue as in https://www.eclipse.org/forums/index.php/t/1088670/. First it was running fine, then I wanted to use as (another) plain user.

Thus, I moved the installation part of "C\users\<admin>\.p2" to the installation folder, and updated eclipse.ini and config.ini as described in https://stackoverflow.com/questions/7070968/eclipse-executable-launcher-error-unable-to-locate-companion-shared-library, citation "as the launcher.library was unreachable by the current user".

However, this leads to the (finally unresolved) error "java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started".

Please fix. It's considered a good style to install applications as an admin and then work as a standard user, isn't it?

For the moment I used the fallback solution "eclipse-jee-2024-12-R-win32-x86_64.zip" which does not require a formal Windows installation. Instead, it is just placed at a convenient place.

Thanks
Dirk

**Comment by merks** [comment]
The installer has this menu:

![image](https://github.com/user-attachments/assets/22a31169-c14d-4c92-8242-3d0d96947915)

You can disable the use of a share bundle pool. 

Or you can choose where to locate the shared bundle pool:

![image](https://github.com/user-attachments/assets/4281e990-5b6c-4903-8a01-ab42b39ed774)

Reading the details here following the "Ask a Question" link would likely be helpful:

https://www.eclipse.org/setups/installer/question/?version=1.35.0%20Build%205959

![image](https://github.com/user-attachments/assets/8e8c9aba-e137-40d0-aa71-d4742d0d090a)

I.e., you should either not use a shared bundle pool or locate it where it is read-only for all users.  The bundle pool cannot simply be moved to another location after the fact.

And yes, if you only plan to create only a single installation, unzipping a package or installing without a pool will produce the same result.
