### ISSUE TITLE
Lots of new warnings in build output

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-packaging/packages#36]
Part of the relase process is to make sure there are no unexpected warnings in the build output. For years now there have been exactly N-1 warnings where N is the number of EPPs.

Now there are hundreds of them with the newest Tycho. Here is a sampling:

- [WARNING] [0be0033b-eaf1-4a41-b53a-ebb526423ec8][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.5] No digest algorithm is available to verify download of binary,epp.package.rcp.executable.gtk.linux.x86_64,4.29.0.20230713-1200.
- [WARNING] The POM for org.osgi:org.osgi.service.prefs:jar:1.1.1-SNAPSHOT is missing, no dependency information available
- WARNING: A terminally deprecated method in java.lang.System has been called
- WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:/home/jenkins/agent/workspace/simrel.epp-tycho-build/org.eclipse.epp.packages/archive-template/target/eclipserun-work/configuration/org.eclipse.osgi/45/0/.cp/lib/antsupportlib.jar)
- WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
- WARNING: System::setSecurityManager will be removed in a future release
- [WARNING] [0be0033b-eaf1-4a41-b53a-ebb526423ec8][extension>org.eclipse.tycho:tycho-maven-plugin:3.0.5] The digest algorithms (md5) used to verify org.eclipse.update.feature,org.eclipse.license,2.0.2.v20181016-2210 have severely compromised security. Please report this concern to the artifact provider.

**Comment by merks** [comment]
You can’t get rid of those md5 warnings. I think p2 needs to be smarter and not complain about checksum for local file system repositories (for the intermediate repositories created by tycho during the build).

**Comment by jonahgraham** [comment]
See 269e7522f520f6ddb31bc5d899db548a20735f7c for where I add these as known ok warnings to the release check-list.
