### ISSUE TITLE
Eclipse 4.28.0 does not support older versions of Lombok 1.18.8

### ISSUE THREAD

**Issue by subhasisbanik** [eclipse-packaging/packages#39]
I have installed the latest version of Eclipse and since my project has already Lombok version of 1.18.8, I am facing issues installing the same version of Lombok in Eclipse.
The latest version of Lombok works though with Eclipse 4.28.0.

Please fix this.

**Comment by merks** [comment]
It's not up to Eclipse to support older versions of anything, it's up to other projects to support the latest version of Eclipse.

https://projectlombok.org/setup/eclipse

**Comment by subhasisbanik** [comment]
@merks  Thanks for the help here!
