### ISSUE TITLE
Suppress warning about "Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'"

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-packaging/packages#53]
Add `--warning=-unknown-keyword` as suggested https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3630#note_1203399 to the tar command

https://github.com/eclipse-packaging/packages/blob/d79ee79a5c4f6ae847834efd91cbad4f5c753133/releng/org.eclipse.epp.config/tools/check-incubating.sh#L11

See also https://github.com/eclipse-tycho/tycho/issues/2586 where I raised the header added in tycho.

**Comment by netomi** [comment]
it should actually be --warning=no-unknown-keyword

at first I had it wrong, according to the tar documentation you have to add a not- prefix to suppress warnings

**Comment by merks** [comment]
The ` --warning=no-unknown-keyword` worked for me.   Be sure to but it before  the -xf and not after it.  😱

**Comment by jonahgraham** [comment]
Thanks @netomi for the updated command line and @merks for the hint.

A further hint to people who have been typing `tar xf file.tar` for their whole life.... to enable using `--warning=no-unknown-keyword` you have to add a `-` before the `xf` (or `tf`) otherwise you get this error:

```
$ tar --warning=no-unknown-keyword tf ~/Downloads/eclipse-cpp-2023-09-RC1-linux-gtk-x86_64.tar.gz 
tar: You must specify one of the '-Acdtrux', '--delete' or '--test-label' options
Try 'tar --help' or 'tar --usage' for more information.
```

**Comment by netomi** [comment]
weird, but good that it worked :D
