### ISSUE TITLE
It's not saving the syntax color settings completely.

### ISSUE THREAD

**Issue by valmirserpa** [eclipse-packaging/packages#54]
Within the Windows/Preferences/Java/Editor/Syntax Coloring menu, I am customizing the colors and font for my code, but for some items, it's not keeping my choices saved.

For example: in Element/Java/Keywords, excluding 'return,' it's not maintaining the bold font I set. I apply my settings, but when I reopen Eclipse, my code doesn't retain the bold font. This also happens with the other elements.

![image](https://github.com/eclipse-packaging/packages/assets/110781631/0e4a5b9a-3efe-4ede-8d74-a1f33eda0a7e)

when i reopen..

![image](https://github.com/eclipse-packaging/packages/assets/110781631/fb97ac2b-15e0-4da0-8ab3-71a648f8de62)

**Comment by jonahgraham** [comment]
Unfortunately I cannot reproduce this with the latest version of Eclipse. Can you provide additional details? e.g. which version of Eclipse and where you got it from and if you have additional plug-ins installed? (e.g. Eclipse for Java Developers 2023-06) The information is available in the Help -> About box, e.g.:

![image](https://github.com/eclipse-packaging/packages/assets/679236/606af52f-dfef-4320-a522-e27684938155)

**Comment by valmirserpa** [comment]
Jonah, this issue occurs when I switch to dark mode. I've recorded my screen to demonstrate how it happens to me.

https://1drv.ms/v/s!AiHuMkEugWVUsgPbT8IYlEmc4vZ7?e=24Z2ce

Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2023-06 (4.28.0)
Build id: 20230608-1333
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Oracle Corporation
Java runtime version: 20.0.1+9-29
Java version: 20.0.1

**Comment by jonahgraham** [comment]
The screen recording was super helpful - thanks! I have moved this bug to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/756 as it appears to be a bug in that Eclipse project.
