### ISSUE TITLE
jakarta.annotation-api_1.3.5.jar not available in Eclipse RCP 2023-09

### ISSUE THREAD

**Issue by tito-cu** [eclipse-packaging/packages#61]
While the jar "jakarta.annotation-api_1.3.5.jar" is available in the 4.29 repository for Eclipse 2023-09: https://download.eclipse.org/eclipse/updates/4.29/R-4.29-202309031000/plugins/

This jar is is not found in the zip for the Eclipse 2023-09 IDE (using "Eclipse IDE for RCP and RAP Developers") downloaded from https://www.eclipse.org/downloads/packages/.
There the jar "javax.annotation_1.3.5.v20200909-1856.jar" is still used (<eclipse_IDE>/plugins + <eclipse_IDE>/artifacts.xml).
This is a problem for people that use "Require Bundle" in the IDE for example.

**Comment by merks** [comment]
See this comment:

https://github.com/eclipse-platform/eclipse.platform/issues/691#issuecomment-1722876393

**Comment by akurtakov** [comment]
My guess for what happens is that:
* Platform uses Import-Package only for javax.annotation package and provides jakarta-annotations bundle in the p2 repo
* There are other bundles in the RCP EPP package that explicitly include javax.annotation 
* For the above reason javax.annotation becomes mandatory bundle for the resolver and which also satisfies Platform Import-Package thus jakarta-annotations is not included in the EPP package

To resolve these included features will have to audited to use Import-Package and/or to explicitly require jakarta-annotations.

**Comment by merks** [comment]
Yes, it's exactly as @akurtakov "guessed".   See audit here:

https://github.com/eclipse-platform/eclipse.platform/issues/691#issuecomment-1722909082

**Comment by akurtakov** [comment]
So an update of XWT (at least) is needed.

**Comment by jonahgraham** [comment]
> This is a problem for people that use "Require Bundle" in the IDE for example.

I think that is outside of the responsibility of the Eclipse Packaging Project - if a project has a require-bundle on some third party library there is no guarantee that library will be included in an EPP produced output.

For the record, there are lots of changes expected to bundle names in the coming months and as all contributing projects make their updates. (e.g. org.apache.commons.io -> org.apache.commons.commons-io as bundle names, but with the same package names).

**Comment by merks** [comment]
There is nothing for which to take action here.   That bundle will generally not be installed in products anymore.
