### ISSUE TITLE
Duplicate keyboard shortcut for Marketplace 'Find' input box and Installed tab

### ISSUE THREAD

**Issue by dsnyderx** [eclipse-packaging/packages#64]
The keyboard shortcut shown on the Eclipse Marketplace Search tab is the 'i' of 'Find'.  However, when using that shortcut in Marketplace, the tab is changed to the 'Installed' tab.

Steps performed:
1. Open Eclipse
2. Select Help->Eclipse Marketplace...
3. Click outside or move the focus out of the Search tab's 'Find' input box
4. Use the keyboard shortkey, ALT+i

Expected behavior:
- Focus moved to the Search tab's 'Find' input box

Actual behavior:
- The Installed tab is shown

Suggested fixes:
- Change the keyboard shortcut to place the focus into the 'Find' input box (e.g., 'ALT+f', 'ALT+n', or 'ALT+d')
- Remove the keyboard shortcut to change to the Installed tab

**Comment by jonahgraham** [comment]
Thanks @dsnyderx for the issue - I have migrated it to the GitHub project that owns this component, please subscribe to that issue to follow along for updates or to make a Pull Request - https://github.com/eclipse-mpc/epp.mpc/issues/1
