### ISSUE TITLE
Add -Djava.security.manager=allow to all packages that contain ant tooling

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-packaging/packages#71]
See discussion on https://github.com/eclipse-platform/eclipse.platform/issues/709.

To avoid errors running ant tooling on Java 21+ (and disallow code running in ant unconditionally exit Eclipse by using `System.exit()`), we should add `-Djava.security.manager=allow` line to eclipse.ini for the affected (most?) packages.

**Comment by jonahgraham** [comment]
Thanks for filing this - part of the EPP release procedure is to ensure that we synchronize such changes:

https://github.com/eclipse-packaging/packages/blob/8b88a53ec2a07b81eb8ada028bd235f4197c310b/RELEASING.md#L47
