### ISSUE TITLE
Run button in Eclipse2023 does not stop previous run of same program

### ISSUE THREAD

**Issue by bpacilio59** [eclipse-packaging/packages#80]
I'm coming from an older version of Eclipse. In that version I could hit the run button and start my Java app. If I saw something wrong I could just go to the editor, make the change, and hit the run button again. It would stop the current program and re-start it. In the 2023 version it launches multiple programs. Is there a setting to change this ?

**Comment by jonahgraham** [comment]
You want this preference: _Run/Debug -> Launching -> Terminate and relaunch[...]_

![image](https://github.com/eclipse-packaging/packages/assets/679236/78eba262-e3e4-4e29-a870-ee59d5aa2c16)

**Comment by bpacilio59** [comment]
Thank you again. Just as a note. I checked my 2018 version and that option was not checked and yet it behaved that way. 

;-)

    On Tuesday, November 7, 2023 at 01:12:57 PM EST, Jonah Graham ***@***.***> wrote:  
 
 


You want this preference: Run/Debug -> Launching -> Terminate and relaunch[...]
