### ISSUE TITLE
Should we discontinue the parallel product?

### ISSUE THREAD

**Issue by merks** [eclipse-packaging/packages#85]
Given the comment here:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3117#note_1391199

And given the outdated content being contributed:

![image](https://github.com/eclipse-packaging/packages/assets/208716/c7b3b67e-2918-46ed-880a-fc4a1e803a91)

Maybe it's time to discontinue this product.

**Comment by jonahgraham** [comment]
@merks this was discussed recently (Aug 2023) on Tools PMC and at that time @jarrah42 [indicated an intention](https://www.eclipse.org/lists/tools-pmc/msg05427.html) to keep maintaining PTP project. The package gets >50% of the number of downloads of other smaller packages like "Eclipse IDE for RCP and RAP Developers" and "Eclipse Modeling Tools"

Is there something about PTP that is out of date in a way that causes an issue? Because AFAIU it is no more or less out of date than the majority of CDT that it depends on. A couple of years ago [we did move org.eclipse.remote](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577097) to CDT to help resolve some significant hurdles to keeping PTP maintained well.

That said, I don't see how we can maintain a project (in Tools TLP) or a package the depends on it if there isn't even a way to build the project now that the JIPP is gone.

**Comment by jonahgraham** [comment]
PS I will raise this issue on Tools PMC too.

**Comment by jonahgraham** [comment]
> PS I will raise this issue on Tools PMC too.

Should be on [this link](https://www.eclipse.org/lists/tools-pmc/msg05442.html) once the list archiver runs.

**Comment by merks** [comment]
It just caught my attention on the help desk issue.   It's hard to tell the difference between outdated and stale versus stable and feature complete...

**Comment by jonahgraham** [comment]
@merks the termination review has started for the ptp project, what timing do you think we should remove this? Should we ditch it for 2023-12?

**Comment by merks** [comment]
I have no strong opinion on this.  Perhaps removing it would be a wake-up call for folks helping to keep the project alive before it's too late?

Of course if we remove the package we should remove/disable the SimRel contributions too.

**Comment by jonahgraham** [comment]
The whole PTP project will be archived just after we release (assuming that no one steps forward to restore PTP during termination review), so removing it now makes sense. 

I'll handle removing it from EPP, can you remove it from SimRel? Feel free to remove from SimRel first.

FYI @jarrah42

**Comment by jarrah42** [comment]
Hi Ed,Unfortunately there’s no-one left to work on it that I know of, so I think the time has come. We can always bring it back if someone volunteers.Regards,GregOn Nov 21, 2023, at 10:44 AM, Ed Merks ***@***.***> wrote:﻿
I have no strong opinion on this.  Perhaps removing it would be a wake-up call for folks helping to keep the project alive before it's too late?
Of course if we remove the package we should remove/disable the SimRel contributions too.

**Comment by merks** [comment]
I would need to disable one of PHP's features too:
```
Cannot complete the install because one or more required items could not be found. Software being installed: validationSet_main 1.0.0 Missing requirement: org.eclipse.php.rdt.sync.feature.group 8.2.0.202311131424 requires 'org.eclipse.equinox.p2.iu; org.eclipse.ptp.rdt.sync.feature.group 0.0.0' but it could not be found Cannot satisfy dependency: mappedRepo_download.eclipse.org_tools_pdt_updates_8.2m3 1.0.0 depends on: org.eclipse.equinox.p2.iu; org.eclipse.php.rdt.sync.feature.group 0.0.0 Cannot satisfy dependency: validationSet_main 1.0.0 depends on: org.eclipse.equinox.p2.iu; mappedRepo_download.eclipse.org_tools_pdt_updates_8.2m3 [1.0.0,1.0.0]
Missing requirement: PHP Development Tools (PDT) Remote Project Synchronization Support 8.2.0.202311131424 (org.eclipse.php.rdt.sync.feature.group 8.2.0.202311131424) requires 'org.eclipse.equinox.p2.iu; org.eclipse.ptp.rdt.sync.feature.group 0.0.0' but it could not be found

InstallableUnit(org.eclipse.ptp.rdt.sync.feature.group) is required by:
  ValidationSet(main)
    Contribution(PDT)
      MappedRepository(https://download.eclipse.org/tools/pdt/updates/8.2m3/)
        Feature(org.eclipse.php.rdt.sync.feature.group)
```
Or just continue to aggregate the one feature.  What do you think?

**Comment by jonahgraham** [comment]
If it's needed it may be best to move that feature to CDT like we did with the rest of PTP that we wanted to keep longer term. I'll have a look to see what that code is to see if CDT wants to adopt. Can you leave that one PTP feature in for now.

@zulus or @jarrah42 if you can save me time and let me know about PDTs use of PTP here that would be helpful. Thanks!

**Comment by jarrah42** [comment]
Sorry, I wasn’t aware of it. GregSent from my iPhoneOn Nov 21, 2023, at 12:26 PM, Jonah Graham ***@***.***> wrote:﻿
If it's needed it may be best to move that feature to CDT like we did with the rest of PTP that we wanted to keep longer term. I'll have a look to see what that code is to see if CDT wants to adopt. Can you leave that one PTP feature in for now.
@zulus or @jarrah42 if you can save me time and let me know about PDTs use of PTP here that would be helpful. Thanks!

**Comment by jonahgraham** [comment]
The parallel package has been removed. As for when PTP is removed from SimRel we should continue that discussion in SimRel's issues.
